name: Firestore Backup

on:
  schedule:
    - cron: '0 5 * * 2'   # 2 AM Argentina Time on Tuesday (UTC+3)
    - cron: '0 5 * * 6'   # 2 AM Argentina Time on Saturday (UTC+3)
  workflow_dispatch:     # Allow manual run

jobs:
  firestore-backup:
    runs-on: ubuntu-latest
    steps:

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}'
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 416.0.0'  # Ensures compatibility with latest features
          project_id: the-bitcoin-hole

      - name: Run Firestore Export
        run: |
          gcloud firestore export gs://the-bitcoin-hole-firestore-backups
